### ISSUE TITLE
[Feature Request] Is it possible to add a `data=` class to the message that belongs to same people?

### ISSUE THREAD

**Issue by Quorafind** [holubj/obsidian-dialogue-plugin#1]
Then we could use css to colorize any people's messages with the same class?

Oh just support colorize option in setting, you could set any people with the same color?

**Comment by holubj** [comment]
Good idea, i'll add the data attributes in the next version!

**Comment by holubj** [comment]
Implemented in version 1.0.1.

Documented here: https://github.com/holubj/obsidian-dialogue-plugin#custom-styles-for-messages
